DROP TABLE TAG_STORY;
DROP TABLE TAG_CARD;
drop table tags;
DROP TABLE STORIES;
DROP TABLE CARDS;
drop table formats;
DROP TABLE SCHEDULE_IMAGE;
DROP TABLE SCHEDULES 
drop table IMAGE_STORY;
drop table images;
drop table profiles;

CREATE TABLE AspNetRoles (
	Id nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	Name nvarchar(256) COLLATE Slovenian_CI_AS NOT NULL,
	CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY (Id)
) 
CREATE  UNIQUE NONCLUSTERED INDEX RoleNameIndex ON dbo.AspNetRoles (  Name ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]

CREATE TABLE AspNetUsers (
	Id nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	Email nvarchar(256) COLLATE Slovenian_CI_AS NULL,
	EmailConfirmed bit NOT NULL,
	PasswordHash nvarchar COLLATE Slovenian_CI_AS NULL,
	SecurityStamp nvarchar COLLATE Slovenian_CI_AS NULL,
	PhoneNumber nvarchar COLLATE Slovenian_CI_AS NULL,
	PhoneNumberConfirmed bit NOT NULL,
	TwoFactorEnabled bit NOT NULL,
	LockoutEndDateUtc datetime NULL,
	LockoutEnabled bit NOT NULL,
	AccessFailedCount int NOT NULL,
	UserName nvarchar(256) COLLATE Slovenian_CI_AS NOT NULL,
	CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY (Id)
)
CREATE  UNIQUE NONCLUSTERED INDEX UserNameIndex ON dbo.AspNetUsers (  UserName ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]

CREATE TABLE AspNetUserClaims (
	Id int IDENTITY(1,1) NOT NULL,
	UserId nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	ClaimType nvarchar COLLATE Slovenian_CI_AS NULL,
	ClaimValue nvarchar COLLATE Slovenian_CI_AS NULL,
	CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY (Id),
	CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE
)
CREATE NONCLUSTERED INDEX IX_UserId ON dbo.AspNetUserClaims (  UserId ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]

CREATE TABLE AspNetUserLogins (
	LoginProvider nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	ProviderKey nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	UserId nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY (LoginProvider,ProviderKey,UserId),
	CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE
)
CREATE NONCLUSTERED INDEX IX_UserId ON dbo.AspNetUserLogins (  UserId ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]

CREATE TABLE AspNetUserRoles (
	UserId nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	RoleId nvarchar(128) COLLATE Slovenian_CI_AS NOT NULL,
	CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY (UserId,RoleId),
	CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY (RoleId) REFERENCES AspNetRoles(Id) ON DELETE CASCADE,
	CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE
)
CREATE NONCLUSTERED INDEX IX_RoleId ON dbo.AspNetUserRoles (  RoleId ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]
CREATE NONCLUSTERED INDEX IX_UserId ON dbo.AspNetUserRoles (  UserId ASC  )  
	WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	ON [PRIMARY ]

CREATE TABLE PROFILES
(
	IDPROFILE INT NOT NULL IDENTITY(1,1),
	FIRSTNAME NVARCHAR(250),
	LASTNAME NVARCHAR(250),
	NICKNAME NVARCHAR(250),
	BIO NVARCHAR(MAX),
	DELETED INT NOT NULL DEFAULT(0),
	USERID NVARCHAR(128) not null,
	CONSTRAINT FKUSER_PROFILE FOREIGN KEY (USERID) REFERENCES AspNetUsers(Id),
	CONSTRAINT PKPROFILES PRIMARY KEY(IDPROFILE)
)
CREATE TABLE IMAGES
(
	IDIMAGE INT NOT NULL IDENTITY(1,1),
	URL NVARCHAR(MAX),
	NAME NVARCHAR(MAX),
	PROFILEID INT NOT NULL,
	SHARED INT NOT NULL DEFAULT(0),
	DELETED INT NOT NULL DEFAULT(0),
	CONSTRAINT PKIMAGES primary key (IDIMAGE),
)
CREATE TABLE FORMATS
(
	IDFORMAT INT NOT NULL IDENTITY(1,1),
	COLOR NVARCHAR(50),
	FONT_SIZE INT DEFAULT(1),
	FONT_FORMAT INT DEFAULT(0),
	LAYOUT INT DEFAULT(1),
	IMG1ID INT,
	IMG2ID INT,
	IMG3ID INT,
	CONSTRAINT FKIMAGE1_FORMATS FOREIGN KEY (IMG1ID) REFERENCES IMAGES(IDIMAGE),
	CONSTRAINT FKIMAGE2_FORMATS FOREIGN KEY (IMG2ID) REFERENCES IMAGES(IDIMAGE),
	CONSTRAINT FKIMAGE3_FORMATS FOREIGN KEY (IMG3ID) REFERENCES IMAGES(IDIMAGE),
	CONSTRAINT PKFORMATS PRIMARY KEY(IDFORMAT)
)
CREATE TABLE TAGS
(
	IDTAG INT NOT NULL IDENTITY(1,1),
	VALUE NVARCHAR(100) NOT NULL,
	TYPE INT NOT NULL,
	CONSTRAINT PKTAGS PRIMARY KEY(IDTAG)
)
CREATE TABLE CARDS
(
	IDCARD INT NOT NULL IDENTITY(1,1),
	NAME NVARCHAR(250),
	SAHRED INT NOT NULL DEFAULT(0),
	DELETED INT NOT NULL DEFAULT(0),
	PROFILEID INT NOT NULL,
	FORMATID INT,
	TAGID INT,
	CONSTRAINT PKCARDS PRIMARY KEY(IDCARD),
	CONSTRAINT FKPROFILES_CARDS FOREIGN KEY(PROFILEID) REFERENCES PROFILES(IDPROFILE),
	CONSTRAINT FKFORMATS_CARDS FOREIGN KEY(FORMATID) REFERENCES FORMATS(IDFORMAT)
)
CREATE TABLE TAG_CARD
(
	IDTAG_CARD INT NOT NULL IDENTITY(1,1),
	TAGID INT NOT NULL,
	CARDID INT NOT NULL,
	CONSTRAINT PKTAG_CARD PRIMARY KEY(IDTAG_CARD),
	CONSTRAINT FKTAG_CARD FOREIGN KEY (TAGID) REFERENCES TAGS(IDTAG),
	CONSTRAINT FKCARD_TAG FOREIGN KEY (CARDID) REFERENCES CARDS(IDCARD)
)
CREATE TABLE STORIES
(
	IDSTORY INT NOT NULL IDENTITY(1,1),
	NAME NVARCHAR(250),
	DESCRIPTION NVARCHAR(MAX),
	THUMBNAIL INT,
	FAVOURITE INT NOT NULL DEFAULT(0),	
	SHARED INT NOT NULL DEFAULT(0),
	DELETED INT NOT NULL DEFAULT(0),
	PROFILEID INT NOT NULL,
	CONSTRAINT PKSTORY PRIMARY KEY(IDSTORY),
	CONSTRAINT FKPROFILE_STORY FOREIGN KEY (PROFILEID) REFERENCES PROFILES(IDPROFILE)
)
CREATE TABLE IMAGE_STORY
(
	IDIMAGE_STORY INT NOT NULL IDENTITY(1,1),
	IMAGEID INT,
	STORYID INT,
	CONSTRAINT FKIMAGE_STORY FOREIGN KEY (IMAGEID) REFERENCES IMAGES(IDIMAGE),
	CONSTRAINT FKSTORY_IMAGE FOREIGN KEY (STORYID) REFERENCES STORIES(IDSTORY),
	CONSTRAINT PKIMAGE_STORZ PRIMARY KEY(IDIMAGE_STORY)
)
CREATE TABLE TAG_STORY
(
	IDTAG_STORY INT NOT NULL IDENTITY(1,1),
	TAGID INT NOT NULL,
	STORYID INT NOT NULL,
	CONSTRAINT PKTAG_STORY PRIMARY KEY(IDTAG_STORY),
	CONSTRAINT FKTAG_STORY FOREIGN KEY (TAGID) REFERENCES TAGS(IDTAG),
	CONSTRAINT FKSTORY_TAG FOREIGN KEY (STORYID) REFERENCES STORIES(IDSTORY)
)
CREATE TABLE SCHEDULES
(
	IDSCHEDULE INT NOT NULL IDENTITY(1,1),
	SCHEDULE_DATE DATE NOT NULL,
	PROFILEID INT,
	CONSTRAINT PKSCHEDULE PRIMARY KEY(IDSCHEDULE),
	CONSTRAINT FKPROFILE_SCHEDULE FOREIGN KEY (PROFILEID) REFERENCES PROFILES(IDPROFILE),
	CONSTRAINT UQSQCEHDULES UNIQUE(SCHEDULE_DATE,PROFILEID)
)
CREATE TABLE SCHEDULE_IMAGE
(
	IDSCHECULDE_IMAGE INT NOT NULL IDENTITY(1,1),
	POSITION INT NOT NULL,
	SCHEDULEID INT NOT NULL,
	IMAGEID INT NOT NULL,
	CONSTRAINT PKSCHEDULE_IMAGE PRIMARY KEY (IDSCHECULDE_IMAGE),
	CONSTRAINT FKSCHEDULE_IMAGE FOREIGN KEY (SCHEDULEID) REFERENCES SCHEDULES(IDSCHEDULE),
	CONSTRAINT FKIMAGE_SCHEDULE FOREIGN KEY (IMAGEID) REFERENCES IMAGES(IDIMAGE)
)