//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR19_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class CARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public CARD()
        {
            this.STORY_CARD = new HashSet<STORY_CARD>();
            this.TAGS = new HashSet<TAG>();
        }
        [JsonProperty(Order = -6)]
        public int IDCARD { get; set; }
        [JsonProperty(Order = -4)]
        public string NAME { get; set; }
        [JsonProperty(Order = -5)]
        public string TEXT { get; set; }
        [JsonIgnore]
        public int DELETED { get; set; }
        [JsonProperty(Order = -5)]
        public int PROFILEID { get; set; }
        [JsonIgnore]
        public Nullable<int> FORMATID { get; set; }
        public int CardOrder { get; set; }
        public int SHARED { get; set; }
        [JsonProperty(Order = -3)]
        public virtual FORMAT FORMAT { get; set; }
        [JsonIgnore]
        public virtual PROFILE PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<STORY_CARD> STORY_CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonProperty(Order = -2)]
        public virtual ICollection<TAG> TAGS { get; set; }
    }
}
