//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR19_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FORMAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMAT()
        {
            this.CARDS = new HashSet<CARD>();
        }

        [JsonIgnore]
        public int IDFORMAT { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> FONT_SIZE { get; set; }
        public Nullable<int> FONT_FORMAT { get; set; }
        public Nullable<int> LAYOUT { get; set; }
        [JsonIgnore]
        public Nullable<int> IMG1ID { get; set; }
        [JsonIgnore]
        public Nullable<int> IMG2ID { get; set; }
        [JsonIgnore]
        public Nullable<int> IMG3ID { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD> CARDS { get; set; }
        [JsonProperty("IMAGE1")]
        public virtual IMAGE IMAGE { get; set; }
        [JsonProperty("IMAGE2")]
        public virtual IMAGE IMAGE1 { get; set; }
        [JsonProperty("IMAGE3")]
        public virtual IMAGE IMAGE2 { get; set; }
    }
}
