//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR19_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HappyPicturesDbContext : DbContext
    {
        public HappyPicturesDbContext()
            : base("name=HappyPicturesDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARD> CARDS { get; set; }
        public virtual DbSet<FORMAT> FORMATS { get; set; }
        public virtual DbSet<IMAGE> IMAGES { get; set; }
        public virtual DbSet<LIKE> LIKES { get; set; }
        public virtual DbSet<PROFILE> PROFILES { get; set; }
        public virtual DbSet<SCHEDULE_IMAGE> SCHEDULE_IMAGE { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULES { get; set; }
        public virtual DbSet<STORy> STORIES { get; set; }
        public virtual DbSet<STORY_CARD> STORY_CARD { get; set; }
        public virtual DbSet<TAG> TAGS { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetAdminID(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetAdminID", emailParameter);
        }
    
        public virtual ObjectResult<GetStoryCards_Result> GetStoryCards(Nullable<int> storyID)
        {
            var storyIDParameter = storyID.HasValue ?
                new ObjectParameter("storyID", storyID) :
                new ObjectParameter("storyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStoryCards_Result>("GetStoryCards", storyIDParameter);
        }
    
        public virtual int CreateUserID(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUserID", emailParameter);
        }
    }
}
