//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR19_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMAGE()
        {
            this.FORMATS = new HashSet<FORMAT>();
            this.FORMATS1 = new HashSet<FORMAT>();
            this.FORMATS2 = new HashSet<FORMAT>();
            this.SCHEDULE_IMAGE = new HashSet<SCHEDULE_IMAGE>();
            this.STORIES = new HashSet<STORy>();
        }
    
        public int IDIMAGE { get; set; }
        public string URL { get; set; }
        public System.DateTime IMGTIMESTAMP { get; set; }
        public int PROFILEID { get; set; }
        public int SHARED { get; set; }
        [JsonIgnore]
        public int DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FORMAT> FORMATS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FORMAT> FORMATS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FORMAT> FORMATS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<SCHEDULE_IMAGE> SCHEDULE_IMAGE { get; set; }
        [JsonIgnore]
        public virtual PROFILE PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<STORy> STORIES { get; set; }
    }
}
