//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR19_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class STORy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORy()
        {
            this.LIKES = new HashSet<LIKE>();
            this.STORY_CARD = new HashSet<STORY_CARD>();
            this.TAGS = new HashSet<TAG>();
        }

        public int IDSTORY { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        [JsonIgnore]
        public Nullable<int> THUMBNAIL { get; set; }
        public int FAVOURITE { get; set; }
        public int SHARED { get; set; }
        [JsonIgnore]
        public int DELETED { get; set; }
        public int PROFILEID { get; set; }
        public int NumberOfLikes { get; set; }

        public virtual IMAGE IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<LIKE> LIKES { get; set; }
        [JsonIgnore]
        public virtual PROFILE PROFILE { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORY_CARD> STORY_CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAGS { get; set; }
    }
}
